import Head from 'next/head'
import { useRouter } from 'next/router'

export default function CohetesList() {

    const router = useRouter();
    const { id } = router.query;

  return (
    <>
      <Head>
        <title>Index de app</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
          <h1>Cohete marca {id}</h1>
      </main>
    </>
  )
}
