import Head from 'next/head'
import styles from '@/styles/Cohetes.module.css';

export default function cohetes() {
  return (
    <>
      <Head>
        <title>Index de cohetes</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
          <h1>lista de cohetes</h1>
      </main>
    </>
  )
}
